### ISSUE TITLE
[Bug]: rocks-config.nvim does not properly load on fresh install

### ISSUE THREAD

**Issue by vhyrro** [nvim-neorocks/rocks-config.nvim#36]
Steps to reproduce:
- Use bootstrapping script to install rocks.nvim
- `:Rocks install kanagawa.nvim`
- `:Rocks install rocks-config.nvim`
- `:Rocks edit` and place the following into the rocks.toml file:
   ```toml
   [config]
   colorscheme = "kanagawa-wave"
   ```

Expected result: the colourscheme is applied

Actual result: nothing happens :p
