### ISSUE TITLE
[Module]: helix-like configuration files

### ISSUE THREAD

**Issue by vhyrro** [nvim-neorocks/rocks-config.nvim#37]
Since we're already using TOML for a lot of things, perhaps it would be wise to create a module that can also manage various aspects of the configuration (options, colourschemes).

I can't settle on a name, as `rocks-config` is taken. This would either parse the `rocks.toml` file or would parse a new, unrelated `config.toml` file with all of the metadata there. This may overlap with nvim-neorocks/rocks.nvim#240.

Example:
```toml

[configuration]
colorscheme = "kanagawa"

[configuration.options]
termguicolors = true
concealcursor = "nv"

```
