### ISSUE TITLE
Colorscheme option is not documented

### ISSUE THREAD

**Issue by flexagoon** [nvim-neorocks/rocks-config.nvim#62]
There is a colorscheme option which lets you do this:

```toml
[config]
colorscheme = "kanagawa"
```

However, it's not documented anywhere
