### ISSUE TITLE
[Feature] Install plugins from bundles

### ISSUE THREAD

**Issue by bottd** [nvim-neorocks/rocks-config.nvim#68]
As a user it would be convenient to configure plugins from alongside bundles. With the current setup we configure a plugin separately from the bundle configuration:

```toml
[plugins]
"neodev.nvim"= "scm"
nvim-lspconfig = { version = "0.1.7" } 

[plugins.nvim-cmp]
git = "hrsh7th/nvim-cmp" # Use the git version of nvim-cmp for the best experience.

[bundles.lsp] # Create a bundle called `lsp`
items = [
    "neodev.nvim",
    "nvim-lspconfig",
    "nvim-cmp"
]
```

Adding a plugin config option like `bundle` could work:

```toml
[plugins]
"neodev.nvim"= { version = "scm", bundle = "lsp"]
nvim-lspconfig = { version = "0.1.7", bundle = "lsp" } 

[plugins.nvim-cmp]
git = "hrsh7th/nvim-cmp" # Use the git version of nvim-cmp for the best experience.
bundle = "lsp"
```

My intuition is that the implementation of bundles also holding plugin config is more work than a `bundle` config solution. However I appreciate bundles for offering structure to plugins in `rocks.toml`. Having plugin config within them would be nice:

```toml
[bundles.lsp.plugins]
"neodev.nvim"= "scm"
nvim-lspconfig = { version = "0.1.7" } 

[bundles.lsp.plugins.nvim-cmp]
git = "hrsh7th/nvim-cmp" # Use the git version of nvim-cmp for the best experience.
```

If not for the `bundles.X.config` this could be shortened slightly to omit plugins:

```toml
[bundles.lsp]
"neodev.nvim"= "scm"
nvim-lspconfig = { version = "0.1.7" } 

[bundles.lsp.nvim-cmp]
git = "hrsh7th/nvim-cmp" # Use the git version of nvim-cmp for the best experience.
```
