### ISSUE TITLE
Main module detection: Support `.lua` and `-lua` suffixes

### ISSUE THREAD

**Issue by danyspin97** [nvim-neorocks/rocks-config.nvim#74]
Currently, I have the following snippet in my `rocks.toml`:

```
[plugins."nvim-colorizer.lua"]
git = "norcalli/nvim-colorizer.lua"
rev = "a065833f35a3a7cc3ef137ac88b5381da2ba302e"
[plugins.colorizer]
config = true
```

nvim-colorizer.lua is installed using `rocks-git`, so it has its own small table with the git reference and the revision. I think it would be helpful to skip `[plugins.colorizer]` and add the config to the plugin table itself. I am not sure if this will be required anymore when most plugins will be available in luarocks, but for the time being it might be interesting to add.

Thanks for the work on rocks.nvim :)

**Comment by mrcjkb** [comment]
Hey :wave: 
The plugin name is `nvim-colorizer.lua`. So this should suffice:

```toml
[plugins."nvim-colorizer.lua"]
git = "norcalli/nvim-colorizer.lua"
rev = "a065833f35a3a7cc3ef137ac88b5381da2ba302e"
config = true
```

I don't think your snippet will work?

**Comment by danyspin97** [comment]
> I don't think your snippet will work?

I moved `nvim-colorizor.lua` from git to luarocks, just to try if rocks-git was making rocks-config fail. The only config that works for me (with both the plugin from git and luarocks) is:

```toml
[plugins.colorizer]
config = true
```
