### ISSUE TITLE
[Feature] Auto setup submodule for a plugin

### ISSUE THREAD

**Issue by danyspin97** [nvim-neorocks/rocks-config.nvim#77]
For the plugin [nvim-scrollview](https://github.com/dstein64/nvim-scrollview), there are a couple of submodules that can be enabled by calling `setup()` on them. Would it be possible to use rocks-config.nvim to enable them?

Working lua config:
```lua
require('scrollview.contrib.gitsigns').setup()
```

Proposed solution:
```toml
[plugins.nvim-scrollview]
git = "dstein64/nvim-scrollview"
rev = "v6.0.0"
config = true

[plugins.scrollview.contrib.gitsigns]
config = true
```
