### ISSUE TITLE
Failed to run 'before' hook

### ISSUE THREAD

**Issue by daniilrozanov** [nvim-neorocks/rocks-config.nvim#81]
What could this error be related to?

```
Failed to run 'before' hook for nvim-cmp: ...cal/share/nvim/rocks/rocks_rtp/lua/rocks-config/init.lua:22: attempt to index local 'opts' (a function value)              
Failed to run 'before' hook for nvim-autopairs: ...cal/share/nvim/rocks/rocks_rtp/lua/rocks-config/init.lua:22: attempt to index local 'opts' (a function value)
```

This error happens only once at the startup and all other time works fine

My config is
```toml
[rocks]

[config]
auto_setup = true

[plugins]
"rocks.nvim" = "2.45.0"
"rocks-git.nvim" = "2.5.3"
"rocks-config.nvim" = "3.1.1"
"rocks-lazy.nvim" = "1.2.0"
"rocks-dev.nvim" = "1.8.0"

"2048.nvim" = "2.8.2"
"auto-hlsearch.nvim" = { version = "1.1.0", event = "CmdlineEnter" }
"better-escape.nvim" = "2.3.3"
"cellular-automaton.nvim" = "scm"
"clangd_extensions.nvim" = "scm"
"comment.nvim" = "0.8.0"
"conform.nvim" = "9.0.0"
"diffview.nvim" = "scm"
"gitsigns.nvim" = "1.0.2"
"lazydev.nvim" = { version = "1.9.0", ft = "lua" }
"leap.nvim" = "scm"
"lspkind.nvim" = "scm"
"lualine.nvim" = "scm"
"lush.nvim" = "scm"
"oil.nvim" = "2.15.0"
"repeat.vim" = "1.2"
"rest.nvim" = "3.13.0"
"substitute.nvim" = "2.0.0"
"telescope-ui-select.nvim" = "scm"
"telescope.nvim" = "scm"
"todo-comments.nvim" = "1.4.0"
"toggleterm.nvim" = "2.13.1"
"which-key.nvim" = "3.17.0"
"zen-mode.nvim" = "1.4.0"
auto-session = "2.5.1"
cmp-buffer = "scm"
cmp-cmdline = "scm"
cmp-git = "scm"
cmp-nvim-lsp = "scm"
cmp-path = "scm"
cmp_luasnip = "scm"
friendly-snippets = "scm"
luasnip = "2.4.0"
neogen = "2.20.0"
neogit = "2.0.0"
neorg = { version = "9.3.0", ft = "norg" }
neorg-conceal-wrap = "1.0.1"
nvim-autopairs = { version = "scm", event = "InsertEnter" }
nvim-bqf = { version = "1.1.1", ft = "qf" }
nvim-cmp = { version = "scm", event = "InsertEnter" }
nvim-dap = "0.10.0"
nvim-dap-ui = "4.0.0"
nvim-dap-virtual-text = "scm"
nvim-treesitter-textobjects = "scm"
nvim-web-devicons = "0.100"
vim-startuptime = "4.5.0"

# Treesitter parsers
tree-sitter-bash = "scm"
# and others ...

[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"
branch = "main"

[bundles.telescope]
items = [
  "telescope.nvim",
  "telescope-ui-select.nvim"
]
config = "bundles.telescope"

[bundles.cmp]
items = [
  "lspkind.nvim",
  "nvim-cmp",
  "cmp-buffer",
  "cmp-cmdline",
  "cmp-nvim-lsp",
  "cmp-path",
  "cmp_luasnip",
  "friendly-snippets",
  "luasnip",
  "nvim-autopairs",
 ]
 config = "bundles.cmp"
```

My `lua/bundles/cmp.lua`
```lua
local lspkind = require "lspkind"
lspkind.init {}

-- LuaSnip
local luasnip = require "luasnip"
luasnip.config.setup {
  history = false,
  updateevents = "TextChanged,TextChangedI",
}
for _, ft_path in ipairs(vim.api.nvim_get_runtime_file("lua/custom/snippets/*.lua", true)) do
  loadfile(ft_path)()
end

require("luasnip.loaders.from_vscode").lazy_load()

-- Cmp
local cmp = require "cmp"

cmp.setup {
  snippet = {
    expand = function(args)
      luasnip.lsp_expand(args.body)
    end,
  },
  completion = { completeopt = "menu,menuone,noinsert" },
  sorting = {
    comparators = {
      cmp.config.compare.offset,
      cmp.config.compare.exact,
      cmp.config.compare.recently_used,
      require "clangd_extensions.cmp_scores",
      cmp.config.compare.kind,
      cmp.config.compare.sort_text,
      cmp.config.compare.length,
      cmp.config.compare.order,
    },
  },
  mapping = cmp.mapping.preset.insert {
    ["<C-d>"] = cmp.mapping.scroll_docs(-4),
    ["<C-f>"] = cmp.mapping.scroll_docs(4),
    -- ["<C-n>"] = cmp.mapping.select_next_item,
    -- ["<C-p>"] = cmp.mapping.select_prev_item,
    ["<C-y>"] = cmp.mapping(cmp.mapping.confirm { select = true }, { "i", "c" }),
    -- Will move you to the right of each of the snippet's expansion locations.
    ["<C-l>"] = cmp.mapping(function()
      if luasnip.expand_or_locally_jumpable() then
        luasnip.expand_or_jump()
      end
    end, { "i", "s" }),
    -- Will move you to the left of each of the snippet's expansion locations.
    ["<C-h>"] = cmp.mapping(function()
      if luasnip.locally_jumpable(-1) then
        luasnip.jump(-1)
      end
    end, { "i", "s" }),
  },
  sources = {
    { name = "nvim_lsp" },
    { name = "luasnip" },
    { name = "path" },
    { name = "buffer" },
  },
}

require("nvim-autopairs").setup {}

-- Automatically add `(` after selecting a function or method
local cmp_autopairs = require "nvim-autopairs.completion.cmp"
cmp.event:on("confirm_done", cmp_autopairs.on_confirm_done())

```
